In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# Shift + enter
print("I love Python & Stats")

I love Python & Stats


In [ ]:
import numpy as np

In [ ]:
np.array([5, 3, 9, 8, 0, 4])

array([5, 3, 9, 8, 0, 4])

In [ ]:
arr = np.array([5, 3, 9, 8, 0, 4])
arr

array([5, 3, 9, 8, 0, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

1

In [ ]:
arr.size

6

In [ ]:
# it is 1D array.
arr.shape

(6,)

In [ ]:
# imp func
arr_new = arr.reshape((1, 6))
arr_new

array([[5, 3, 9, 8, 0, 4]])

In [ ]:
arr_new.ndim

2

In [ ]:
arr_new.shape

(1, 6)

In [ ]:
arr_new.reshape(6,1)

array([[5],
       [3],
       [9],
       [8],
       [0],
       [4]])

In [ ]:
np.array([[1,2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr

array([5, 3, 9, 8, 0, 4])

In [ ]:
arr + 10

array([15, 13, 19, 18, 10, 14])

In [ ]:
arr_sq = arr**2
arr_sq

array([25,  9, 81, 64,  0, 16])

In [ ]:
arr

array([5, 3, 9, 8, 0, 4])

In [ ]:
# np.add()

In [ ]:
# changes the arr array with squares element
# arr = arr**2

In [ ]:
arr2 = np.array( [[2.3, 7.1, 11.5], [4.4, 8, 2]], dtype= float)
arr2

array([[ 2.3,  7.1, 11.5],
       [ 4.4,  8. ,  2. ]])

In [ ]:
arr2 = np.array( [[2.3, 7.1, 11.5], [4.4, 8, 2]], dtype = int )
arr2

array([[ 2,  7, 11],
       [ 4,  8,  2]])

In [ ]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [ ]:
a = np.arange(-5, 9, 1.5)
a

array([-5. , -3.5, -2. , -0.5,  1. ,  2.5,  4. ,  5.5,  7. ,  8.5])

In [ ]:
a.astype(int)

array([-5, -3, -2,  0,  1,  2,  4,  5,  7,  8])

In [ ]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.zeros(6).astype('int')

array([0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(6).reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
nums = np.arange(1, 17)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
nums.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
nums.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
nums.reshape(4,3)

ValueError: cannot reshape array of size 16 into shape (4,3)

In [ ]:
(5)

5

In [ ]:
(5,)

(5,)

In [ ]:
arr

array([5, 3, 9, 8, 0, 4])

In [ ]:
arr[0]

5

In [ ]:
arr[3]

8

In [ ]:
arr[-1]

4

In [ ]:
arr[-3]

8

In [ ]:
arr

array([5, 3, 9, 8, 0, 4])

In [ ]:
# Slicing
arr[1:4]

array([3, 9, 8])

In [ ]:
arr[1:5]

array([3, 9, 8, 0])

In [ ]:
arr[-4:-1]

array([9, 8, 0])

In [ ]:
# arr[start:end:step]
arr[1:6:2]

array([3, 8, 4])

In [ ]:
arr

array([5, 3, 9, 8, 0, 4])

In [ ]:
arr[:5]

array([5, 3, 9, 8, 0])

In [ ]:
arr[2:]

array([9, 8, 0, 4])

In [ ]:
# arr[0:5]==arr[:5]??

In [ ]:
arr[:]

array([5, 3, 9, 8, 0, 4])

In [ ]:
nums = nums.reshape(4, 4)
nums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
nums[0,0]

1

In [ ]:
nums[3,3]

16

In [ ]:
nums[-1, -1]

16

In [ ]:
nums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
nums[1:3 , 1: ]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [ ]:
nums[ :3 , :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

## Fancy Indexing/ Boolean Indexing

In [ ]:
nums = np.array([6, 3, 9, 1, 10, 4, 7, 12])
nums

array([ 6,  3,  9,  1, 10,  4,  7, 12])

In [ ]:
# boolean values.
nums > 5

array([ True, False,  True, False,  True, False,  True,  True])

In [ ]:
mask = nums > 5
mask

array([ True, False,  True, False,  True, False,  True,  True])

In [ ]:
nums[mask]

array([ 6,  9, 10,  7, 12])

In [ ]:
mask = nums>5
nums[mask]

array([ 6,  9, 10,  7, 12])

In [ ]:
nums[nums>5]

array([ 6,  9, 10,  7, 12])

In [ ]:
nums

array([ 6,  3,  9,  1, 10,  4,  7, 12])

In [ ]:
nums[nums%2==0]

array([ 6, 10,  4, 12])

In [ ]:
# nums.reshape(16)

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 1, 2, 2])

In [ ]:
a+b

array([2, 3, 5, 6])

In [ ]:
a*b

array([1, 2, 6, 8])

In [ ]:
a==b

array([ True, False, False, False])

In [ ]:
mat1 = np.array([[2,4], [1,3]])
mat1

array([[2, 4],
       [1, 3]])

In [ ]:
mat2 = np.array([[2, 4, 1], [1,2,3]])
mat2

array([[2, 4, 1],
       [1, 2, 3]])

In [ ]:
np.matmul(mat1, mat2)

array([[ 8, 16, 14],
       [ 5, 10, 10]])

In [ ]:
# Dot Product

np.dot(mat1, mat2)

array([[ 8, 16, 14],
       [ 5, 10, 10]])

In [ ]:
np.dot(2, 3)

6

In [ ]:
# +
# np.add()

# -
# np.subtract()

In [ ]:
nums

array([ 6,  3,  9,  1, 10,  4,  7, 12])

In [ ]:
nums.sum()

52

In [ ]:
nums.mean()

6.5

In [ ]:
nums.max()

12

In [ ]:
np.sum(nums)

52

In [ ]:
np.mean(nums)

6.5

In [ ]:
mat = np.arange(1, 16).reshape(3, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np.sum(mat)

120

In [ ]:
np.sum(mat, axis=1)

array([15, 40, 65])

In [ ]:
np.sum(mat, axis=0)

array([18, 21, 24, 27, 30])

In [ ]:
np.mean(mat)

8.0

In [ ]:
np.mean(mat, axis=1)

array([ 3.,  8., 13.])

In [ ]:
nums

array([ 6,  3,  9,  1, 10,  4,  7, 12])

In [ ]:
np.sort(nums)

array([ 1,  3,  4,  6,  7,  9, 10, 12])

In [ ]:
nums

array([ 6,  3,  9,  1, 10,  4,  7, 12])

In [ ]:
# nums = np.sort(nums)

In [ ]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np.transpose(mat)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [ ]:
mat.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [ ]:
a = np.tile(np.arange(0,40,10), (3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
b = np.tile(np.arange(0,3), (4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b = np.array([0, 1, 2]).reshape(1, 3)
b

array([[0, 1, 2]])

In [ ]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
birds = np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock'])
birds

array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw',
       'parrot', 'macaw', 'peacock'], dtype='<U7')

In [ ]:
ages = np.array([[6, 1, 6, 5, 7, 6, 0, 9, 0, 7]])
ages

array([[6, 1, 6, 5, 7, 6, 0, 9, 0, 7]])

In [ ]:
ages.max()

9

In [ ]:
np.max(ages)

9

In [ ]:
np.argmax(ages)

7

In [ ]:
birds[7]

'parrot'